name: Despliegue AWS Terraform

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subes cambios a la rama main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Build'
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar tu c√≥digo
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    # 3. Inicializar (Descargar plugins de AWS)
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    # 4. Aplicar los cambios
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1